export type DailyCharEntry = {
  char: string;
  pinyin: string;
  meaning: string;
  quote: string;
  source: string;
  en: string;
};

export const DAILY_CHARS: DailyCharEntry[] = [
  {
    char: "空",
    pinyin: "kōng",
    meaning: "观缘起而不执著，心地自然宽明。",
    quote: "色即是空，空即是色。",
    source: "《心经》",
    en: "Form is emptiness, emptiness is form.",
  },
  {
    char: "净",
    pinyin: "jìng",
    meaning: "身心澄明时，所处之境也随之清净。",
    quote: "心净则国土净。",
    source: "《维摩诘经》",
    en: "When the mind is pure, the land is pure.",
  },
  {
    char: "慈",
    pinyin: "cí",
    meaning: "以温柔善意安乐众生。",
    quote: "慈能与乐，悲能拔苦。",
    source: "《大智度论》",
    en: "Compassion gives joy; mercy removes suffering.",
  },
  {
    char: "悲",
    pinyin: "bēi",
    meaning: "见苦知苦，发愿拔济一切。",
    quote: "同体大悲，无缘大慈。",
    source: "《梵网经》",
    en: "Great compassion embraces all as one body.",
  },
  {
    char: "喜",
    pinyin: "xǐ",
    meaning: "随顺正法而生欢喜光明。",
    quote: "法喜充满，禅悦为食。",
    source: "《无量寿经》",
    en: "Filled with the joy of Dharma, nourished by meditative bliss.",
  },
  {
    char: "舍",
    pinyin: "shě",
    meaning: "放下执取，得自在平等。",
    quote: "放下即自在，舍得即得。",
    source: "祖师语",
    en: "Let go — and freedom follows.",
  },
  {
    char: "觉",
    pinyin: "jué",
    meaning: "返照自心，离迷见真。",
    quote: "觉而不迷，正而不邪。",
    source: "《六祖坛经》",
    en: "Awakened and not confused; upright and not deviant.",
  },
  {
    char: "定",
    pinyin: "dìng",
    meaning: "外不逐境，内心安住。",
    quote: "外离相即禅，内不乱即定。",
    source: "《六祖坛经》",
    en: "Unattached outwardly is Chan; undisturbed inwardly is samadhi.",
  },
  {
    char: "忍",
    pinyin: "rěn",
    meaning: "以柔和定力承受逆境，不失本心。",
    quote: "忍辱波罗蜜，能除百种苦。",
    source: "《金刚经》",
    en: "The perfection of patience dispels a hundred sufferings.",
  },
  {
    char: "戒",
    pinyin: "jiè",
    meaning: "守护身口意，使道心有根。",
    quote: "戒为无上菩提本，应当具足持净戒。",
    source: "《梵网经》",
    en: "Precepts are the root of supreme awakening.",
  },
  {
    char: "念",
    pinyin: "niàn",
    meaning: "念念回光，常住当下清明。",
    quote: "念念不离心，心心皆是佛。",
    source: "祖师语",
    en: "Thought after thought, never apart from the mind — each mind is Buddha.",
  },
  {
    char: "善",
    pinyin: "shàn",
    meaning: "止恶行善，使心行端正。",
    quote: "诸恶莫作，众善奉行。",
    source: "《法句经》",
    en: "Refrain from all evil; practice all good.",
  },
  {
    char: "慧",
    pinyin: "huì",
    meaning: "观照实相，明辨是非，不为迷惑所转。",
    quote: "戒定慧三学，是佛道根本。",
    source: "《法句经》",
    en: "Precepts, concentration, and wisdom are the root of the Buddhist path.",
  },
  {
    char: "禅",
    pinyin: "chán",
    meaning: "静坐观心，直指本来面目。",
    quote: "禅者，佛之心也。",
    source: "《马祖语录》",
    en: "Chan is the mind of Buddha.",
  },
  {
    char: "悟",
    pinyin: "wù",
    meaning: "一念回光，顿见本心，迷云自散。",
    quote: "迷时师度，悟了自度。",
    source: "《六祖坛经》",
    en: "When confused, the teacher ferries you; when awakened, you ferry yourself.",
  },
  {
    char: "法",
    pinyin: "fǎ",
    meaning: "宇宙万象的运行规律，也是离苦得乐的道路。",
    quote: "法尚应舍，何况非法。",
    source: "《金刚经》",
    en: "Even the Dharma should be let go of — how much more so what is not Dharma.",
  },
  {
    char: "心",
    pinyin: "xīn",
    meaning: "万法根本，一切苦乐皆由此生，亦由此灭。",
    quote: "三界唯心，万法唯识。",
    source: "《华严经》",
    en: "The three realms are only mind; the ten thousand dharmas are only consciousness.",
  },
  {
    char: "明",
    pinyin: "míng",
    meaning: "无明散尽，心光自显，如日出云开。",
    quote: "明心见性，见性成佛。",
    source: "《六祖坛经》",
    en: "Illuminate the mind, see the nature — seeing the nature is Buddhahood.",
  },
  {
    char: "真",
    pinyin: "zhēn",
    meaning: "不假不虚，本来如此，超越一切造作。",
    quote: "真如自性，无来无去。",
    source: "《楞严经》",
    en: "True suchness — neither coming nor going.",
  },
  {
    char: "如",
    pinyin: "rú",
    meaning: "如其所是，不增不减，平等无别。",
    quote: "如如不动，了了常知。",
    source: "祖师语",
    en: "Unmoved in suchness, yet vividly aware.",
  },
  {
    char: "性",
    pinyin: "xìng",
    meaning: "本来清净，不生不灭，是万法的根源。",
    quote: "自性本自清净，自性能生万法。",
    source: "《六祖坛经》",
    en: "The self-nature is originally pure; it can give rise to all phenomena.",
  },
  {
    char: "圆",
    pinyin: "yuán",
    meaning: "圆满无缺，不偏不倚，遍照十方。",
    quote: "一月普现一切水，一切水月一月摄。",
    source: "《永嘉证道歌》",
    en: "One moon is reflected in all waters; all water-moons are contained in one moon.",
  },
  {
    char: "寂",
    pinyin: "jì",
    meaning: "动静自如，不被外境所扰，安住本然。",
    quote: "寂而常照，照而常寂。",
    source: "祖师语",
    en: "Still yet ever illuminating; illuminating yet ever still.",
  },
  {
    char: "智",
    pinyin: "zhì",
    meaning: "照了实相，善辨善恶，能断无明烦恼。",
    quote: "般若如大火，能烧一切烦恼薪。",
    source: "《大智度论》",
    en: "Prajna is like a great fire — it burns all the fuel of affliction.",
  },
  {
    char: "精",
    pinyin: "jīng",
    meaning: "精勤不懈，不退不散，道业由此成就。",
    quote: "精进勤修，如救头燃。",
    source: "《佛遗教经》",
    en: "Practice diligently, as if your head were on fire.",
  },
  {
    char: "进",
    pinyin: "jìn",
    meaning: "不停歇地向善向上，一步一步走向解脱。",
    quote: "若勤精进，则事无难者。",
    source: "《佛遗教经》",
    en: "If you practice diligently, nothing is too difficult.",
  },
  {
    char: "施",
    pinyin: "shī",
    meaning: "以欢喜心给予，不求回报，广结善缘。",
    quote: "布施如播种，福田由此生。",
    source: "《大宝积经》",
    en: "Giving is like planting seeds — a field of merit grows from it.",
  },
  {
    char: "度",
    pinyin: "dù",
    meaning: "从此岸渡至彼岸，从苦到乐，从迷到悟。",
    quote: "自度度人，自觉觉他。",
    source: "《梵网经》",
    en: "First liberate yourself, then liberate others; first awaken, then awaken others.",
  },
  {
    char: "缘",
    pinyin: "yuán",
    meaning: "万法因缘和合而生，无一独立存在。",
    quote: "此有故彼有，此生故彼生。",
    source: "《杂阿含经》",
    en: "This being, that is; this arising, that arises.",
  },
  {
    char: "因",
    pinyin: "yīn",
    meaning: "种善因得善果，一切结果皆有其根源。",
    quote: "欲知过去因，今生受者是；欲知未来果，今生作者是。",
    source: "《三世因果经》",
    en: "To know past causes, look at present results; to know future results, look at present actions.",
  },
  {
    char: "果",
    pinyin: "guǒ",
    meaning: "善有善报，因果不虚，应慎护三业。",
    quote: "假使百千劫，所作业不亡；因缘会遇时，果报还自受。",
    source: "《大宝积经》",
    en: "Though a thousand eons pass, deeds do not perish — when conditions meet, results are received.",
  },
  {
    char: "福",
    pinyin: "fú",
    meaning: "行善积德，福德自然随之而来。",
    quote: "福由心造，祸由心生。",
    source: "《地藏经》",
    en: "Blessings are created by the mind; misfortune is also born from the mind.",
  },
  {
    char: "德",
    pinyin: "dé",
    meaning: "内在的品质与修为，是真正的财富。",
    quote: "积善之家，必有余庆。",
    source: "《易经》",
    en: "A family that accumulates goodness will surely have abundant blessings.",
  },
  {
    char: "苦",
    pinyin: "kǔ",
    meaning: "了知苦的真相，才能生起出离与悲悯之心。",
    quote: "苦集灭道，是为四谛。",
    source: "《转法轮经》",
    en: "Suffering, its origin, its cessation, the path — these are the Four Noble Truths.",
  },
  {
    char: "乐",
    pinyin: "lè",
    meaning: "真正的快乐来自内心清净，而非外境满足。",
    quote: "知足常乐，以道自娱。",
    source: "《佛遗教经》",
    en: "Contentment is lasting joy; find delight in the Way itself.",
  },
  {
    char: "无",
    pinyin: "wú",
    meaning: "不执有无，超越二边，体会无所不包的开阔。",
    quote: "无无明，亦无无明尽。",
    source: "《般若心经》",
    en: "No ignorance, and also no ending of ignorance.",
  },
  {
    char: "安",
    pinyin: "ān",
    meaning: "安于当下，不求不扰，心自得其所。",
    quote: "平常心是道。",
    source: "《马祖语录》",
    en: "The ordinary mind is the Way.",
  },
  {
    char: "住",
    pinyin: "zhù",
    meaning: "安住正念，不被妄想牵引。",
    quote: "应无所住而生其心。",
    source: "《金刚经》",
    en: "Give rise to a mind that dwells nowhere.",
  },
  {
    char: "转",
    pinyin: "zhuǎn",
    meaning: "转烦恼为菩提，化逆境为助缘。",
    quote: "若能转物，即同如来。",
    source: "《楞严经》",
    en: "If you can turn things, you are the same as the Tathagata.",
  },
  {
    char: "归",
    pinyin: "guī",
    meaning: "回归本心，一切道路终将回到原点。",
    quote: "万法归一，一归何处？",
    source: "祖师语",
    en: "Ten thousand things return to one — where does the one return?",
  },
  {
    char: "信",
    pinyin: "xìn",
    meaning: "信为道源功德母，发心修行的第一步。",
    quote: "信为道元功德母，长养一切诸善法。",
    source: "《华严经》",
    en: "Faith is the source of the path and mother of virtue, nurturing all wholesome dharmas.",
  },
  {
    char: "愿",
    pinyin: "yuàn",
    meaning: "发宏愿度化众生，愿力是修行最深的动力。",
    quote: "众生无边誓愿度，烦恼无尽誓愿断。",
    source: "《四弘誓愿》",
    en: "Sentient beings are numberless — I vow to liberate them all.",
  },
  {
    char: "行",
    pinyin: "xíng",
    meaning: "解行并重，知而不行非真知。",
    quote: "空谈无益，力行乃道。",
    source: "祖师语",
    en: "Empty talk is worthless — the Way lies in practice.",
  },
  {
    char: "持",
    pinyin: "chí",
    meaning: "受持正法，守护戒律，不令散失。",
    quote: "受持读诵，为人演说。",
    source: "《金刚经》",
    en: "Receive, uphold, read, recite, and expound it to others.",
  },
  {
    char: "光",
    pinyin: "guāng",
    meaning: "智慧之光照破无明，不灭不增。",
    quote: "无量光，无量寿，光明遍照十方。",
    source: "《阿弥陀经》",
    en: "Boundless light, boundless life — illuminating all the ten directions.",
  },
  {
    char: "道",
    pinyin: "dào",
    meaning: "通向解脱的路，也是万物运行的规律。",
    quote: "平常心是道，行住坐卧皆道场。",
    source: "《马祖语录》",
    en: "The ordinary mind is the Way — walking, standing, sitting, lying — all are practice.",
  },
  {
    char: "悦",
    pinyin: "yuè",
    meaning: "修行之中自有喜悦，非外求所得。",
    quote: "法喜充满，禅悦为食。",
    source: "《无量寿经》",
    en: "Filled with the joy of Dharma, nourished by meditative bliss.",
  },
  {
    char: "清",
    pinyin: "qīng",
    meaning: "心地清明，一尘不染，自然自在。",
    quote: "清净心中常寂照，如月映千江。",
    source: "祖师语",
    en: "In a pure mind there is constant still illumination — like the moon reflected in a thousand rivers.",
  },
  {
    char: "息",
    pinyin: "xī",
    meaning: "妄念息处，本心显现，呼吸即是道场。",
    quote: "息心即是道，何须更觅佛。",
    source: "祖师语",
    en: "Where the mind rests, that is the Way — why search further for Buddha?",
  },
  {
    char: "本",
    pinyin: "běn",
    meaning: "追根究底，回到最初清净的本来面目。",
    quote: "本来面目，父母未生前是什么？",
    source: "祖师语",
    en: "What was your original face before your parents were born?",
  },
  {
    char: "了",
    pinyin: "liǎo",
    meaning: "了然通透，无所障碍，彻见实相。",
    quote: "了即业障本来空，未了应须还宿债。",
    source: "《永嘉证道歌》",
    en: "When awakened, karmic obstacles are originally empty; not yet awakened, one must repay old debts.",
  },
  {
    char: "照",
    pinyin: "zhào",
    meaning: "以觉照观察内心，不被妄念遮蔽。",
    quote: "照见五蕴皆空，度一切苦厄。",
    source: "《般若心经》",
    en: "Illuminating and perceiving that the five aggregates are empty, one transcends all suffering.",
  },
  {
    char: "观",
    pinyin: "guān",
    meaning: "如实观察身心，不逃避，不执著。",
    quote: "观自在菩萨，行深般若波罗蜜多时。",
    source: "《般若心经》",
    en: "The Bodhisattva Avalokiteshvara, practicing deep prajna-paramita...",
  },
];

export function getTodayChar(): DailyCharEntry {
  const index = Math.floor(Date.now() / 86_400_000) % DAILY_CHARS.length;
  return DAILY_CHARS[index];
}
